apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-runtime-dev
nameSuffix: -dev

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/environment: dev

resources:
  - ../../base
  - namespace.yaml

secretGenerator:
  - name: ai-runtime-secrets
    envs:
      - .env.runtime.secrets

images:
  - name: registry.example.com/alibaba-llm-ai-runtime
    newName: ghcr.io/k1ddy/alibaba-llm-ai-runtime
    newTag: main
