apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-runtime-dev
nameSuffix: -dev

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/environment: dev

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: image-pull-secret-patch.yaml
  - path: llm-config-patch.yaml

secretGenerator:
  - name: ai-runtime-secrets
    envs:
      - .env.runtime.secrets

images:
  - name: registry.example.com/alibaba-llm-ai-runtime
    newName: crpi-ir1o22efjphtqr94-vpc.cn-hangzhou.personal.cr.aliyuncs.com/llm-ai-runtime/alibaba-llm-ai-runtime
    newTag: sha-816c14f
